name: Run tests

on: [ pull_request ] 

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up MSYS2 and Mingw
      if: matrix.os == 'windows-latest'
      uses: msys2/setup-msys2@v2
      with:
        update: true
      
    - name: Build the library
      run: make build
      
    - name: Run tests
      run: make test
