name: Run tests

on: [pull_request]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}

    env:
      CC: ${{ matrix.cc }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        cc: [gcc, clang]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install libcriterion-dev
        sudo apt-get install valgrind

    - name: Install Dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew update
        brew tap LouisBrunner/valgrind
        brew install criterion
        brew install --HEAD LouisBrunner/valgrind/valgrind

    - name: Build the library
      run: make

    - name: Run tests
      run: make test

    - name: Check memory leaks
      run: make memory
