name: Run tests

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up MSYS2 and Mingw
      if: matrix.os == 'windows-latest'
      uses: msys2/setup-msys2@v2
      with:
        update: true

    - name: Set up dependencies
      run: sh install_test_dependencies.sh
      
    - name: Build and test
      run: |
        make mkdir
        make test
